version: "3.8"
services:
  blitzvideoapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blitzvideo
    ports:
      - 8001:8000
    volumes:
      - .:/app
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: Blitzvideo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Blitzcode123.
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"